Feature/refactor for reduced complexity
diana-hep/excursion pull request #11
Opened 2021-08-09 12:09 UTC by tutrie

2021-08-09 14:53 UTC, irinaespejo commented on .gitignore
> +>>>>>>> gpu
Suggestion: remove `.gitignore` altogether. This is _legacy_ from my GPyTorch excursion repo, sorry.

2021-08-09 14:54 UTC, irinaespejo commented on .idea/.gitignore
> +/workspace.xml
Same as with `.gitignore`, _legacy_ PyCharm file. Suggestion: remove

2021-08-09 15:05 UTC, irinaespejo requested changes
Here are my suggestions of files to remove. Mostly legacy hidden files. Please also add to delete `assets/example_cjs_1.png` and `assets/example_cjs.png` duplicates. 
Migrate travis CI to Github Actions, see comment for link to reusable code.

2021-08-09 15:37 UTC, irinaespejo commented on examples/data/limit_expected_values.csv
> +500,90,0.09709346771666667
Suggestion: remove file, sorry this is from a real-world application of excursion legacy. But it shouldn't be in this first merge.

2021-08-09 15:37 UTC, irinaespejo commented on examples/data/limit_observed_values.csv
> +500,90,0.07591295527371135
Suggestion: remove file, sorry this is from a real-world application of excursion legacy. But it shouldn't be in this first merge.

2021-08-09 15:38 UTC, irinaespejo commented on examples/data/monosbb_2sigma.csv
> +312373,3500,200,130,2.69,3.91,2.91,2.09,1.51,1.12
Suggestion: remove file, sorry this is from a real-world application of excursion legacy. But it shouldn't be in this first merge.

2021-08-09 15:38 UTC, irinaespejo commented on examples/data/truth_level_data_1/sensitivity.csv
> +41,2000.0,200.0,90.0,1.0,0.25,4.08784199966
Suggestion: remove file, sorry this is from a real-world application of excursion legacy. But it shouldn't be in this first merge.

2021-08-09 15:40 UTC, irinaespejo commented on examples/data/truth_level_4D.csv
> +62,1315.0,127.0,494.0,0.25,0.2588440592247573,,
Suggestion: remove file, sorry this is from a real-world application of excursion legacy. But it shouldn't be in this first merge.

2021-08-09 15:47 UTC, irinaespejo requested changes
Suggestion: remove all binary files listed below. Sorry, they are legacy from a project but they shouldn't be in a first PR.

- examples/data/susy-EricRun__v2.root
- examples/data/truth_level_data_1/Truth level input for learning with dark Higgs model (bug-fixed).pdf
- examples/data/truth_level_data_1/sensitivity_contour.png
- In results/ there ideally there should be only one folder. For isntance the one showing results from a jupyter notebook run. I don;t know if this is the case. My suggestion is to remove unnecessary results/ folders and leave to your criteria which ones to preserve

2021-08-09 16:40 UTC, irinaespejo requested changes
Files to remove:
- examples/unfactored/mean_with_test_obs.pdf
- examples/unfactored/pairplot_raw_data.pdf

2021-08-09 19:39 UTC, irinaespejo requested changes
# review-excursion-pr

## `examples/basic_tutorial.ipynb`

Problem 1: Learner() tries to finds a GPU and fails. There should be a device agnostic snippet. Users will run this code both on gpus and cpus
![](https://i.imgur.com/0HyxNzJ.png)

Suggestion: mae it device agnostic, this is a standard way of doing it
![](https://i.imgur.com/UZ0KNx6.png)

and in ExcursionProblem class
![](https://i.imgur.com/G4iw5YW.png)
Users will forget about putting 'cpu' or 'cuda' in `algorithm_opts.yaml`, it's better an automated decision.


No other  problems observed. The 3D case doesn;t converge but probably just needs more iterations, it's fine. We also need to think about better metrics but that's fine for now.
I suggest incorporating a simple test in `pytest` that checks that the notebook `tutorial_basics.ipynb` ends succesfully.


## `examples/benchmark_1d.ipynb` and  `examples/benchmark_2d.ipynb`

Problem: when running this cell
![](https://i.imgur.com/nzGqHbm.png)

this error shows up
![](https://i.imgur.com/4mgjwml.png)

Suggestion: 
I think this notebook might be outdated since it doesn;t use the ExcursionProblem() class and uses module import instead.

## `examples/unfactored/`
Unsure if this folder was intended for debugging. Is it's not relevant remove all files.

## TO DO for next PR include MultipleFunctions support (not for now)

2021-08-09 19:44 UTC, irinaespejo commented on excursion/_diagnosis/__init__.py
> +    return confusion_list, predlabels_list, truelabels_list, diagX, labels
Unsure why the folder is called `_diagnosis/` what does the underscore mean here?

2021-08-09 19:45 UTC, irinaespejo commented on excursion/_diagnosis/__init__.py
> +torch.cuda.set_device(0)
sorry this line is legacy from my code, suggestion: delete

2021-08-09 19:45 UTC, irinaespejo commented on excursion/_diagnosis/old_init_.py
> +    return {name: c(X,y_list,gps,scandetails) for name,c in callbacks.items()}
I assume this is legacy code from my repo. Let's remove it so that the PR is cleaner

2021-08-09 19:47 UTC, irinaespejo commented on excursion/_diagnosis/old_samplers.py
> +                        scandetails.rangedef[i][0],
This file is handy to preserve. I would rename it to `samplers.py` instead of `old_samplers.py` so that we know it is not legacy but actual useful code. Not sure if it should be under `_diagnosis` but fine for now.

2021-08-09 20:12 UTC, irinaespejo requested changes
More comments on core files of the refactoring

2021-08-09 20:12 UTC, irinaespejo commented on excursion/acquisition/PES.py
> +        return X_pointsgrid[self.get_first_max_index(gp, X_pointsgrid, acq_cand_vals)]
ok I see the utility of `_acquire` here. Same comment with torch.clone. The code for PES looks good to me.

2021-08-09 20:12 UTC, irinaespejo commented on excursion/acquisition/base.py
> +        return self
We don't use acquisition function with parameters, that would be a bit meta. Let's erase the method if you can't give a use case.

2021-08-09 20:12 UTC, irinaespejo commented on excursion/acquisition/base.py
> +class AcquisitionFunction(object):
Also, why is there no __init__ method?

2021-08-09 20:12 UTC, irinaespejo commented on excursion/excursion.py
> +
self.device = device ?? with device coming from

if cuda available:
       device = torch.device('cuda')
else:
      device = torch.device('cpu')
If you have another way of incorporating device lmk

2021-08-09 20:12 UTC, irinaespejo commented on excursion/learner.py
> +        raise NotImplementedError()
We discussed `_Learner` in a meeting and agreed to remove? @lukasheinrich  @tutrie

2021-08-09 20:17 UTC, irinaespejo commented on excursion/unfactored/madgraph5atlasval/.gitmodules
> +	url = https://github.com/diana-hep/excursion.git
Everything under the folder 'excursion/madgraph5atlasval/' should get removed, legacy :fire: :page_facing_up:

2021-08-09 20:29 UTC, irinaespejo commented on testing/algorithm_specs.yaml
> +  batchsize: None
ok the `testing/` folder is legacy but should stay to make unit tests with pytest. I'm gonna put the refactoring of the `testing/` folder to adapt it to your code in a TO DO list. No action to take for now.

2021-08-09 20:32 UTC, irinaespejo commented on excursion/unfactored/checkmate.py
> +X = torch.from_numpy(X_plot)
Should the `unfactored/` folder get :fire: ? I think so, we have completely changed the testcase import module in favor of ExcrusionProblem class

2021-08-09 20:41 UTC, tutrie commented on excursion/acquisition/base.py
> +class AcquisitionFunction(object):
No init since it is an abstract interface and not an abstract object. this ensures all the future acq classes which implement it will be able to use the ask-and-tell API

2021-08-09 20:42 UTC, irinaespejo commented on excursion/models/base.py
> +        Parameters
A Gaussian Process has hyperparameters and GPyTorch takes control of that. I'm unsure what parameters `set_params` refers to.

2021-08-09 20:43 UTC, tutrie commented on excursion/excursion.py
> +
device comes from the algorithm options. bit convoluted at the moment i think... also this was an oversight bc it should not always be torch.float64, unless it should?

2021-08-09 20:48 UTC, tutrie commented on excursion/models/base.py
> +        Parameters
this is responsible for setting the initial parameters in the builders. it simplifies constructing objects for use with the ask and tell api. they dont have to change the learner or the optimizer. just make a new acquisition function and model and can do custom stuff with very little work. I can create an example, with botorch maybe?

2021-08-09 20:51 UTC, irinaespejo commented on excursion/models/gp.py
> +                .sample(torch.Size([])).to(device=self.device, dtype=self.dtype)
It's better to put NotImplementedError here.
The issue is subtle, when there is a noisy observation it means that querying the black box function ans receiving `target_observed = target_true + epsilon`. Epsilon is a random variable and everytime it is queried like in  MultivariateNormal(torch.zeros(len(targets)), torch.eye(len(targets))) it will _give a different error_ :warning: 
This can introduce bugs along the way because if we are querying `target_observed` anywhere else in the code they are going to be different quantities :exclamation:

2021-08-09 20:57 UTC, irinaespejo commented on excursion/optimize/estimator_backup.py
> +from .builders import build_sampler, build_model, build_acquisition_func
Why have two folders `_optimize/` and `optimize/` ?

2021-08-09 21:01 UTC, irinaespejo commented on excursion/optimize/builders.py
> +            acq_function = PES()
PES() should, at least,  get the same arguments as MES: device=kwargs['device'], dtype=kwargs['dtype']

2021-08-09 21:06 UTC, tutrie commented on excursion/optimize/builders.py
> +            acq_function = PES()
it does, set_params takes care of it. I will change it was an oversight

2021-08-09 21:07 UTC, irinaespejo requested changes
Last comments

2021-08-10 13:38 UTC, irinaespejo commented on excursion/acquisition/base.py
> +class AcquisitionFunction(object):
:heavy_check_mark:

2021-08-10 13:42 UTC, irinaespejo commented on excursion/excursion.py
> +
If it's too much hassle let's leave the device and dtype like that but please remmeber to add it to the ongoing TO DO list in this issue #12 

end :heavy_check_mark:

2021-08-10 14:56 UTC, irinaespejo commented on excursion/models/base.py
> +        Parameters
If you could create a _very simple_ use case for this, that'd be helpful. Thank you!
Before creating an example, maybe the famous diagram connecting the classes and objects is enough for me to understand the utility.

2021-08-10 14:56 UTC, irinaespejo commented on excursion/optimize/builders.py
> +            acq_function = PES()
cool 

end :heavy_check_mark:

2021-08-12 13:54 UTC, irinaespejo commented on excursion/models/gp.py
> +                .sample(torch.Size([])).to(device=self.device, dtype=self.dtype)
discussed on Slack, y(x) is only called once. no action to take

end :heavy_check_mark:

2021-08-16 19:20 UTC, closed without merging